name: CI

on:
  push:
    branches: [main, feat/*]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Lua 5.2
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.2"

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Run List Module Tests
        run: |
          cd tests
          lua test_list.lua

      - name: Run Recipe Module Tests
        run: |
          cd tests
          lua test_recipe.lua

      - name: Run Technology Module Tests
        run: |
          cd tests
          lua test_technology.lua

      - name: Test Summary
        run: |
          echo "✅ All tests completed successfully!"
          echo "📊 Test Coverage:"
          echo "  - List Module: 30 tests"
          echo "  - Recipe Module: 9 tests"
          echo "  - Technology Module: 23+ tests"
          echo "  - Total: 62+ tests"
