name: CI

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    name: Test Matrix
    strategy:
      matrix:
        lua-version: ["5.2", "5.4"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Lua ${{ matrix.lua-version }}
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.lua-version }}

      - name: Run All Tests
        run: |
          echo "🧪 Running tests with Lua ${{ matrix.lua-version }}"
          cd tests

          echo "Testing List Module..."
          lua test_list.lua

          echo "Testing Recipe Module..."
          lua test_recipe.lua

          echo "Testing Technology Module..."
          lua test_technology.lua

          echo "✅ All tests passed with Lua ${{ matrix.lua-version }}!"

      - name: Test Summary
        run: |
          echo "📊 Test Coverage (Lua ${{ matrix.lua-version }}):"
          echo "  - List Module: 30 tests"
          echo "  - Recipe Module: 9 tests"
          echo "  - Technology Module: 23+ tests"
          echo "  - Total: 62+ tests"
          echo "✅ All tests passed for Lua ${{ matrix.lua-version }}!"
